# Generated by Django 5.2.2 on 2025-06-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Введите тему письма",
                        null=True,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Введите содержимое письма",
                        null=True,
                        verbose_name="Содержание письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите почтовый адрес получателя",
                        max_length=254,
                        verbose_name="Почтовый адрес получателя",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        help_text="Введите ФИО", verbose_name="ФИО получателя"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["fullname"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        help_text="Укажите дату и время начала рассылки",
                        verbose_name="Время и дата начала рассылки",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        help_text="Укажите дату и время окончания рассылки",
                        verbose_name="Время и дата окончания рассылки",
                    ),
                ),
                (
                    "mailing_status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("running", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        help_text="Выберите статус рассылки",
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messenger",
                        to="messenger.message",
                        verbose_name="Сообщение рассылки",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        to="messenger.recipient", verbose_name="Получатель рассылки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
