# Generated by Django 5.2.2 on 2025-06-10 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sending_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Фиксация даты и времени отправки рассылки",
                    ),
                ),
                (
                    "sending_status",
                    models.CharField(
                        choices=[
                            ("successfully", "Успешно"),
                            ("unsuccessfully", "Не успешно"),
                        ],
                        verbose_name="Статус отправки рассылки",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(
                        max_length=150, verbose_name="Ответ почтового сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messenger.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
    ]
