# Generated by Django 5.2.2 on 2025-06-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_mailingattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
