# Generated by Django 5.2.2 on 2025-06-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0005_alter_message_recipient_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(
                help_text="Введите почтовый адрес получателя",
                max_length=254,
                unique=True,
                verbose_name="Почтовый адрес получателя",
            ),
        ),
    ]
