# Generated by Django 5.2.2 on 2025-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0006_alter_recipient_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Введите почтовый адрес получателя",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Почтовый адрес получателя",
            ),
        ),
    ]
