# Generated by Django 5.2.2 on 2025-06-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0008_mailing_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_statistics", "can view statistics"),
                    ("can_disable_mailing", "can disable mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
